import { createClient } from "@supabase/supabase-js";

const supabaseUrl = "https://qavpleanmjbxbwfzismp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhdnBsZWFubWpieGJ3Znppc21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5MzkyOTgsImV4cCI6MjEwMDUxNTI5OH0.8ch0D-p019xHw17DzIfa-k_2GXT_I49jfd1rAwPjKh4";

const supabase = createClient(supabaseUrl, supabaseKey);

const REAL_MENU_ITEMS = [
  // 1. DESAYUNOS Y MERIENDAS
  {
    id: "des-chico",
    name: "Desayuno / Merienda Chico",
    price: 3000,
    takeaway_price: 2700,
    delivery_price: 3300,
    description: "Café, Cortado o Lágrima + 1 medialuna y 1 criollito",
    category: "desayunos_meriendas",
    tags: ["Desayuno", "Merienda"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 220,
    allergens: ["Gluten", "Lácteos"],
    stock: 50,
    is_available: true
  },
  {
    id: "des-jarro",
    name: "Desayuno / Merienda Jarro",
    price: 3500,
    takeaway_price: 3150,
    delivery_price: 3850,
    description: "Café, Cortado o Lágrima en Jarro + 1 medialuna y 1 criollito",
    category: "desayunos_meriendas",
    tags: ["Desayuno", "Merienda"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 260,
    allergens: ["Gluten", "Lácteos"],
    stock: 50,
    is_available: true
  },
  {
    id: "des-grande",
    name: "Desayuno / Merienda Grande",
    price: 5500,
    takeaway_price: 4950,
    delivery_price: 6050,
    description: "Café, Cortado o Lágrima + 2 medialunas y 2 criollitos",
    category: "desayunos_meriendas",
    tags: ["Desayuno", "Merienda", "Completo"],
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 450,
    allergens: ["Gluten", "Lácteos"],
    stock: 50,
    is_available: true
  },
  {
    id: "des-submarino-capuchino",
    name: "Submarino / Capuchino Especial",
    price: 6000,
    takeaway_price: 5400,
    delivery_price: 6600,
    description: "Submarino de chocolate o Capuchino + 2 medialunas y 2 criollitos",
    category: "desayunos_meriendas",
    tags: ["Especial", "Chocolate"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 480,
    allergens: ["Gluten", "Lácteos"],
    stock: 40,
    is_available: true
  },
  {
    id: "des-te",
    name: "Servicio de Té Completo",
    price: 4500,
    takeaway_price: 4050,
    delivery_price: 4950,
    description: "Té (consultar variedades) + 2 medialunas y 2 criollitos",
    category: "desayunos_meriendas",
    tags: ["Té", "Merienda"],
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 320,
    allergens: ["Gluten", "Lácteos"],
    stock: 40,
    is_available: true
  },
  {
    id: "des-super-completo",
    name: "Desayuno / Merienda Súper Completo",
    price: 7000,
    takeaway_price: 6300,
    delivery_price: 7700,
    description: "Doble, Submarino, Capuchino o Té con tostadas, manteca, mermelada o dulce de leche y jugo de naranja",
    category: "desayunos_meriendas",
    tags: ["Súper Completo", "Recomendado"],
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 550,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },

  // 2. PROMOS
  {
    id: "pro-tostado",
    name: "Promo Infusión + Tostado",
    price: 10000,
    takeaway_price: 9000,
    delivery_price: 11000,
    description: "Infusión fría o caliente + tostado mixto de jamón y queso",
    category: "desayunos_meriendas",
    tags: ["Promo", "Tostado"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 520,
    allergens: ["Gluten", "Lácteos"],
    stock: 40,
    is_available: true
  },
  {
    id: "pro-huevos-jamon",
    name: "Promo Infusión + Huevos Revueltos y Jamón",
    price: 12000,
    takeaway_price: 10800,
    delivery_price: 13200,
    description: "Infusión fría o caliente + 2 huevos revueltos, 2 fetas de jamón y 2 fetas de queso",
    category: "desayunos_meriendas",
    tags: ["Promo", "Proteico"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 480,
    allergens: ["Huevo", "Lácteos"],
    stock: 40,
    is_available: true
  },

  // 3. EMPANADAS Y PIZZAS
  {
    id: "emp-carne",
    name: "Empanada de Carne",
    price: 2000,
    takeaway_price: 1800,
    delivery_price: 2200,
    description: "Empanada criolla de carne cortada a cuchillo",
    category: "empanadas",
    tags: ["Empanadas", "Carne"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 250,
    allergens: ["Gluten"],
    stock: 60,
    is_available: true
  },
  {
    id: "emp-pollo",
    name: "Empanada de Pollo",
    price: 2000,
    takeaway_price: 1800,
    delivery_price: 2200,
    description: "Empanada de pollo sazonada",
    category: "empanadas",
    tags: ["Empanadas", "Pollo"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 230,
    allergens: ["Gluten"],
    stock: 60,
    is_available: true
  },
  {
    id: "emp-jq",
    name: "Empanada de Jamón y Queso",
    price: 2000,
    takeaway_price: 1800,
    delivery_price: 2200,
    description: "Empanada hojaldrada de jamón y muzzarella",
    category: "empanadas",
    tags: ["Empanadas"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 260,
    allergens: ["Gluten", "Lácteos"],
    stock: 60,
    is_available: true
  },
  {
    id: "emp-caprese",
    name: "Empanada Caprese",
    price: 2000,
    takeaway_price: 1800,
    delivery_price: 2200,
    description: "Empanada de muzzarella, tomate fresco y albahaca",
    category: "empanadas",
    tags: ["Empanadas", "Vegetariano"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 220,
    allergens: ["Gluten", "Lácteos"],
    stock: 60,
    is_available: true
  },

  // PIZZAS
  {
    id: "piz-mozzarella",
    name: "Pizza Mozzarella",
    price: 14000,
    takeaway_price: 12600,
    delivery_price: 15400,
    description: "Mozzarella, orégano y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Clásico"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 850,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "piz-mozzarella-doble",
    name: "Pizza Mozzarella Doble",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella doble, orégano y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Doble Queso"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 1050,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "piz-anchoa",
    name: "Pizza Anchoa",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, anchoas y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Anchoas"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 890,
    allergens: ["Gluten", "Lácteos", "Pescado"],
    stock: 25,
    is_available: true
  },
  {
    id: "piz-morron",
    name: "Pizza Morrón",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, morrón asado y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 870,
    allergens: ["Gluten", "Lácteos"],
    stock: 25,
    is_available: true
  },
  {
    id: "piz-jamon",
    name: "Pizza Jamón",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, jamón y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 920,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "piz-especial",
    name: "Pizza Especial",
    price: 17000,
    takeaway_price: 15300,
    delivery_price: 18700,
    description: "Mozzarella, jamón, morrón y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Especial"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 960,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "piz-roquefort",
    name: "Pizza Roquefort",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, queso roquefort y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Roquefort"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 980,
    allergens: ["Gluten", "Lácteos"],
    stock: 25,
    is_available: true
  },
  {
    id: "piz-napolitana",
    name: "Pizza Napolitana",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, rodajas de tomate, orégano y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Napolitana"],
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 890,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "piz-albahaca",
    name: "Pizza Albahaca",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, tomate picado, albahaca fresca y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Fresca"],
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 880,
    allergens: ["Gluten", "Lácteos"],
    stock: 25,
    is_available: true
  },
  {
    id: "piz-fugazza",
    name: "Pizza Fugazza",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Mozzarella, abundante cebolla rehogada y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Fugazza"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 910,
    allergens: ["Gluten", "Lácteos"],
    stock: 25,
    is_available: true
  },
  {
    id: "piz-palmito",
    name: "Pizza Palmito",
    price: 18000,
    takeaway_price: 16200,
    delivery_price: 19800,
    description: "Mozzarella, palmitos, salsa golf y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Especial"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 990,
    allergens: ["Gluten", "Lácteos"],
    stock: 20,
    is_available: true
  },
  {
    id: "piz-brasilera",
    name: "Pizza Brasilera",
    price: 18000,
    takeaway_price: 16200,
    delivery_price: 19800,
    description: "Mozzarella, ananá, azúcar morena y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Agridulce"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 950,
    allergens: ["Gluten", "Lácteos"],
    stock: 20,
    is_available: true
  },
  {
    id: "piz-rucula",
    name: "Pizza Rúcula y Jamón Crudo",
    price: 18000,
    takeaway_price: 16200,
    delivery_price: 19800,
    description: "Mozzarella, rúcula fresca, jamón crudo y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Gourmet"],
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 940,
    allergens: ["Gluten", "Lácteos"],
    stock: 25,
    is_available: true
  },

  // 4. PASTAS
  {
    id: "pas-noquis",
    name: "Ñoquis de Papa o Espinaca",
    price: 8500,
    takeaway_price: 7650,
    delivery_price: 9350,
    description: "Ñoquis caseros con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 550,
    allergens: ["Gluten", "Huevo"],
    stock: 30,
    is_available: true
  },
  {
    id: "pas-ravioles",
    name: "Ravioles Caseros",
    price: 9000,
    takeaway_price: 8100,
    delivery_price: 9900,
    description: "Ravioles caseros con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 580,
    allergens: ["Gluten", "Huevo"],
    stock: 30,
    is_available: true
  },
  {
    id: "pas-canelones",
    name: "Canelones Caseros",
    price: 8500,
    takeaway_price: 7650,
    delivery_price: 9350,
    description: "Canelones caseros rellenos con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 620,
    allergens: ["Gluten", "Huevo", "Lácteos"],
    stock: 25,
    is_available: true
  },
  {
    id: "pas-tallarines",
    name: "Tallarines Caseros",
    price: 8500,
    takeaway_price: 7650,
    delivery_price: 9350,
    description: "Tallarines caseros al huevo con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 520,
    allergens: ["Gluten", "Huevo"],
    stock: 30,
    is_available: true
  },

  // 5. AL PLATO
  {
    id: "pla-milanesa",
    name: "Milanesa al Plato (Ternera o Pollo)",
    price: 7000,
    takeaway_price: 6300,
    delivery_price: 7700,
    description: "Milanesa dorada de ternera o pollo servida al plato",
    category: "minutas_carnes",
    tags: ["Al Plato", "Milanesa"],
    image: "https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 580,
    allergens: ["Gluten", "Huevo"],
    stock: 40,
    is_available: true
  },
  {
    id: "pla-milanesa-napolitana",
    name: "Milanesa Napolitana al Plato",
    price: 8000,
    takeaway_price: 7200,
    delivery_price: 8800,
    description: "Milanesa de ternera o pollo a la napolitana con salsa de tomate, jamón y queso fundido",
    category: "minutas_carnes",
    tags: ["Al Plato", "Napolitana"],
    image: "https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 720,
    allergens: ["Gluten", "Huevo", "Lácteos"],
    stock: 35,
    is_available: true
  },
  {
    id: "pla-carre-cerdo",
    name: "Carré de Cerdo (2 unidades)",
    price: 8000,
    takeaway_price: 7200,
    delivery_price: 8800,
    description: "2 unidades de carré de cerdo doradas y jugosas a la plancha",
    category: "minutas_carnes",
    tags: ["Al Plato", "Cerdo"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 640,
    allergens: [],
    stock: 25,
    is_available: true
  },
  {
    id: "pla-costeleta-ternera",
    name: "Costeleta de Ternera (1 unidad)",
    price: 5000,
    takeaway_price: 4500,
    delivery_price: 5500,
    description: "1 costeleta de ternera tierna sazonada a la plancha",
    category: "minutas_carnes",
    tags: ["Al Plato", "Ternera"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 450,
    allergens: [],
    stock: 30,
    is_available: true
  },

  // 6. GUARNICIONES
  {
    id: "gua-papas-fritas",
    name: "Papas Fritas",
    price: 5000,
    takeaway_price: 4500,
    delivery_price: 5500,
    description: "Porción de papas fritas bastón doradas y crocantes",
    category: "minutas_carnes",
    tags: ["Guarnición", "Papas"],
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 420,
    allergens: [],
    stock: 50,
    is_available: true
  },
  {
    id: "gua-papas-huevo",
    name: "Papas Fritas con Huevo Revuelto",
    price: 8000,
    takeaway_price: 7200,
    delivery_price: 8800,
    description: "Papas fritas crocantes coronadas con huevo revuelto",
    category: "minutas_carnes",
    tags: ["Guarnición", "Especial"],
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 580,
    allergens: ["Huevo"],
    stock: 40,
    is_available: true
  },
  {
    id: "gua-pure",
    name: "Puré de Papa o Puré Mixto",
    price: 5000,
    takeaway_price: 4500,
    delivery_price: 5500,
    description: "Puré cremoso casero de papa o mixto (papa y zapallo)",
    category: "minutas_carnes",
    tags: ["Guarnición", "Puré"],
    image: "https://images.unsplash.com/photo-1514944288352-fffac99f0bdf?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 280,
    allergens: ["Lácteos"],
    stock: 40,
    is_available: true
  },
  {
    id: "gua-huevo-frito",
    name: "Huevo Frito (1 unidad)",
    price: 1000,
    takeaway_price: 900,
    delivery_price: 1100,
    description: "1 unidad de huevo frito a punto",
    category: "minutas_carnes",
    tags: ["Guarnición"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 90,
    allergens: ["Huevo"],
    stock: 60,
    is_available: true
  },
  {
    id: "gua-arroz",
    name: "Arroz Amarillo o Blanco c/ Queso y Crema",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Arroz amarillo sazonado o arroz blanco servido con queso y crema",
    category: "minutas_carnes",
    tags: ["Guarnición", "Arroz"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 310,
    allergens: ["Lácteos"],
    stock: 40,
    is_available: true
  },
  {
    id: "gua-ensalada-mixta",
    name: "Ensalada Mixta",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Tomate, lechuga, zanahoria y huevo",
    category: "minutas_carnes",
    tags: ["Ensalada", "Fresca"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 140,
    allergens: ["Huevo"],
    stock: 40,
    is_available: true
  },
  {
    id: "gua-ensalada-completa",
    name: "Ensalada Completa",
    price: 7000,
    takeaway_price: 6300,
    delivery_price: 7700,
    description: "Tomate, lechuga, remolacha, zanahoria, rúcula, huevo, jamón, queso y pollo",
    category: "minutas_carnes",
    tags: ["Ensalada", "Completa"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 380,
    allergens: ["Huevo", "Lácteos"],
    stock: 30,
    is_available: true
  },

  // 7. LOMITOS
  {
    id: "lom-simple",
    name: "Lomito Simple c/ Papas (Ternera o Pollo)",
    price: 12000,
    takeaway_price: 10800,
    delivery_price: 13200,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón y queso. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Lomito", "Con Papas"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 820,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 35,
    is_available: true
  },
  {
    id: "lom-completo",
    name: "Lomito Completo c/ Papas (Ternera o Pollo)",
    price: 13000,
    takeaway_price: 11700,
    delivery_price: 14300,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso y huevo frito. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Lomito", "Completo"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 910,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 35,
    is_available: true
  },
  {
    id: "lom-teatro",
    name: "Lomito del Teatro c/ Papas",
    price: 14000,
    takeaway_price: 12600,
    delivery_price: 15400,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso, huevo frito, morrón y cebolla salteada. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Lomito", "Especial de la Casa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 1020,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 30,
    is_available: true
  },

  // 8. HAMBURGUESAS
  {
    id: "ham-simple",
    name: "Hamburguesa Simple c/ Papas",
    price: 10000,
    takeaway_price: 9000,
    delivery_price: 11000,
    description: "Lechuga, tomate, mayonesa, jamón y queso. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Hamburguesa", "Con Papas"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 780,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 40,
    is_available: true
  },
  {
    id: "ham-completa",
    name: "Hamburguesa Completa c/ Papas",
    price: 11000,
    takeaway_price: 9900,
    delivery_price: 12100,
    description: "Lechuga, tomate, mayonesa, jamón, queso y huevo frito. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Hamburguesa", "Completa"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 870,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 40,
    is_available: true
  },
  {
    id: "ham-teatro",
    name: "Hamburguesa del Teatro c/ Papas",
    price: 12000,
    takeaway_price: 10800,
    delivery_price: 13200,
    description: "Lechuga, tomate, mayonesa, jamón, queso, huevo frito, morrón y cebolla salteada. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Hamburguesa", "Especial de la Casa"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 980,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 35,
    is_available: true
  },

  // 9. SÁNDWICHES DE MILANESA
  {
    id: "san-milanesa-simple",
    name: "Sándwich de Milanesa Simple c/ Papas",
    price: 11000,
    takeaway_price: 9900,
    delivery_price: 12100,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón y queso. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Sándwich", "Milanesa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 840,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 35,
    is_available: true
  },
  {
    id: "san-milanesa-completa",
    name: "Sándwich de Milanesa Completa c/ Papas",
    price: 12000,
    takeaway_price: 10800,
    delivery_price: 13200,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso y huevo frito. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Sándwich", "Milanesa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 920,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 35,
    is_available: true
  },
  {
    id: "san-milanesa-teatro",
    name: "Sándwich de Milanesa del Teatro c/ Papas",
    price: 13000,
    takeaway_price: 11700,
    delivery_price: 14300,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso, huevo frito, morrón y cebolla salteada. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Sándwich", "Especial de la Casa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 1040,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 30,
    is_available: true
  },

  // 10. SÁNDWICHES FRÍOS Y OTROS
  {
    id: "san-miga-2u",
    name: "Sándwiches de Miga (2 unidades)",
    price: 7000,
    takeaway_price: 6300,
    delivery_price: 7700,
    description: "2 unidades de sándwich de miga + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Miga"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 420,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "san-arabe",
    name: "Sándwich Árabe (Jamón o Milanesa)",
    price: 6000,
    takeaway_price: 5400,
    delivery_price: 6600,
    description: "Sándwich en pan árabe con jamón o milanesa + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Árabe"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 460,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },
  {
    id: "san-pebete",
    name: "Pebete (Jamón o Milanesa)",
    price: 6000,
    takeaway_price: 5400,
    delivery_price: 6600,
    description: "Pebete tierno de jamón y queso o milanesa + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Pebete"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 440,
    allergens: ["Gluten", "Lácteos"],
    stock: 35,
    is_available: true
  },
  {
    id: "san-pebeton",
    name: "Pebetón Gigante (Jamón o Milanesa)",
    price: 7000,
    takeaway_price: 6300,
    delivery_price: 7700,
    description: "Pebetón de gran tamaño con jamón o milanesa + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Pebetón"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 580,
    allergens: ["Gluten", "Lácteos"],
    stock: 30,
    is_available: true
  },

  // 11. MENÚ EJECUTIVO
  {
    id: "exe-para-llevar",
    name: "Menú Ejecutivo (Para Llevar)",
    price: 8000,
    takeaway_price: 8000,
    delivery_price: 8800,
    description: "Plato principal del día preparado para llevar",
    category: "executive",
    tags: ["Menú Ejecutivo", "Para Llevar"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 650,
    allergens: [],
    stock: 50,
    is_available: true
  },
  {
    id: "exe-mesa-bebida",
    name: "Menú Ejecutivo + Bebida (En Mesa)",
    price: 12000,
    takeaway_price: 10800,
    delivery_price: 13200,
    description: "Plato principal del día + bebida de la casa para consumo en salón",
    category: "executive",
    tags: ["Menú Ejecutivo", "Salón"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 720,
    allergens: [],
    stock: 50,
    is_available: true
  },
  {
    id: "exe-completo",
    name: "Menú Ejecutivo Completo (Plato + Bebida + Postre)",
    price: 16000,
    takeaway_price: 14400,
    delivery_price: 17600,
    description: "Plato principal del día + bebida + postre a elección para consumo en salón",
    category: "executive",
    tags: ["Menú Ejecutivo", "Completo"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 880,
    allergens: [],
    stock: 50,
    is_available: true
  },

  // 12. BEBIDAS Y POSTRES
  // Jugos y Licuados
  {
    id: "beb-licuado-frutal",
    name: "Jugo / Licuado Frutal",
    price: 6000,
    takeaway_price: 5400,
    delivery_price: 6600,
    description: "Durazno, Banana, Frutilla o Multifrutas al agua o con leche",
    category: "bebidas_sa",
    tags: ["Licuado", "Frutas"],
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 210,
    allergens: ["Lácteos"],
    stock: 50,
    is_available: true
  },

  // Gaseosas y Aguas
  {
    id: "beb-gaseosa-lata",
    name: "Gaseosa / Agua en Lata 354 ml",
    price: 3000,
    takeaway_price: 2700,
    delivery_price: 3300,
    description: "Variedades de gaseosas o agua en lata 354 ml",
    category: "bebidas_sa",
    tags: ["Bebidas", "Sin Alcohol"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 140,
    allergens: [],
    stock: 100,
    is_available: true
  },
  {
    id: "beb-gaseosa-500",
    name: "Gaseosa / Agua Botella 500 ml",
    price: 3500,
    takeaway_price: 3150,
    delivery_price: 3850,
    description: "Botella individual de 500 ml",
    category: "bebidas_sa",
    tags: ["Bebidas", "Sin Alcohol"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 180,
    allergens: [],
    stock: 100,
    is_available: true
  },
  {
    id: "beb-gaseosa-1L",
    name: "Gaseosa Botella 1 L / 1.25 L",
    price: 7000,
    takeaway_price: 6300,
    delivery_price: 7700,
    description: "Botella grande de 1 Litro / 1.25 Litros",
    category: "bebidas_sa",
    tags: ["Bebidas", "Familiar"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 420,
    allergens: [],
    stock: 60,
    is_available: true
  },
  {
    id: "beb-gatorade",
    name: "Gatorade / Powerade 500 ml",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Bebida isotónica hidratante 500 ml",
    category: "bebidas_sa",
    tags: ["Bebidas", "Isotónica"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 120,
    allergens: [],
    stock: 50,
    is_available: true
  },

  // Cervezas, Vinos y Tragos
  {
    id: "alc-cerveza-lata-473",
    name: "Cerveza en Lata 473 ml",
    price: 3500,
    takeaway_price: 3150,
    delivery_price: 3850,
    description: "Cerveza rubia en lata de 473 ml",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Lata"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 210,
    allergens: ["Gluten"],
    stock: 80,
    is_available: true
  },
  {
    id: "alc-quilmes-1L",
    name: "Cerveza Quilmes 1 L",
    price: 7500,
    takeaway_price: 6750,
    delivery_price: 8250,
    description: "Cerveza Quilmes de 1 Litro retornable bien helada",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "1 Litro"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 430,
    allergens: ["Gluten"],
    stock: 50,
    is_available: true
  },
  {
    id: "alc-quilmes-stout-ipa",
    name: "Cerveza Quilmes Stout / IPA 1 L",
    price: 8000,
    takeaway_price: 7200,
    delivery_price: 8800,
    description: "Cerveza Quilmes especial Stout negra o IPA de 1 Litro",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Especial"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 460,
    allergens: ["Gluten"],
    stock: 40,
    is_available: true
  },
  {
    id: "alc-andes-1L",
    name: "Cerveza Andes 1 L",
    price: 8000,
    takeaway_price: 7200,
    delivery_price: 8800,
    description: "Cerveza Andes Origen de 1 Litro bien fría",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "1 Litro"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 440,
    allergens: ["Gluten"],
    stock: 40,
    is_available: true
  },
  {
    id: "alc-brahma-1L",
    name: "Cerveza Brahma 1 L",
    price: 7500,
    takeaway_price: 6750,
    delivery_price: 8250,
    description: "Cerveza Brahma de 1 Litro bien helada",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "1 Litro"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 420,
    allergens: ["Gluten"],
    stock: 50,
    is_available: true
  },
  {
    id: "alc-stella-heineken-1L",
    name: "Cerveza Stella Artois / Heineken 1 L",
    price: 8000,
    takeaway_price: 7200,
    delivery_price: 8800,
    description: "Cerveza Stella Artois o Heineken Premium de 1 Litro",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Premium"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 440,
    allergens: ["Gluten"],
    stock: 40,
    is_available: true
  },
  {
    id: "alc-corona-chica",
    name: "Cerveza Corona Chica (330 ml)",
    price: 5500,
    takeaway_price: 4950,
    delivery_price: 6050,
    description: "Porrón de cerveza Corona 330 ml servido con limón",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Porrón"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 150,
    allergens: ["Gluten"],
    stock: 50,
    is_available: true
  },
  {
    id: "alc-corona-grande",
    name: "Cerveza Corona Grande (710 ml)",
    price: 6500,
    takeaway_price: 5850,
    delivery_price: 7150,
    description: "Botella de cerveza Corona 710 ml servida con limón",
    category: "bebidas_alcohol",
    tags: ["Cerveza"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 320,
    allergens: ["Gluten"],
    stock: 40,
    is_available: true
  },
  {
    id: "alc-vino-botella",
    name: "Vino en Botella (750 ml)",
    price: 9000,
    takeaway_price: 8100,
    delivery_price: 9900,
    description: "Vino de la casa seleccionado en botella 750 ml",
    category: "bebidas_alcohol",
    tags: ["Vino"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 520,
    allergens: [],
    stock: 30,
    is_available: true
  },
  {
    id: "alc-vino-copa",
    name: "Vino en Copa",
    price: 3000,
    takeaway_price: 2700,
    delivery_price: 3300,
    description: "Copa de vino varietal de la casa",
    category: "bebidas_alcohol",
    tags: ["Vino", "Copa"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 120,
    allergens: [],
    stock: 50,
    is_available: true
  },
  {
    id: "alc-fernet",
    name: "Fernet Branca con Coca",
    price: 6000,
    takeaway_price: 5400,
    delivery_price: 6600,
    description: "Trago de Fernet Branca helado preparado con Coca-Cola",
    category: "bebidas_alcohol",
    tags: ["Trago", "Fernet", "Favorito"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 240,
    allergens: [],
    stock: 50,
    is_available: true
  },
  {
    id: "alc-gancia",
    name: "Gancia con Limón",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Trago aperitivo Gancia servido con hielo y rodaja de limón",
    category: "bebidas_alcohol",
    tags: ["Trago", "Aperitivo"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 180,
    allergens: [],
    stock: 50,
    is_available: true
  },

  // Postres
  {
    id: "pos-budin-pan",
    name: "Budín de Pan Casero",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Budín de pan casero con dulce de leche o crema",
    category: "postres",
    tags: ["Postre", "Casero"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 320,
    allergens: ["Gluten", "Lácteos", "Huevo"],
    stock: 30,
    is_available: true
  },
  {
    id: "pos-flan-casero",
    name: "Flan Casero Tradicional",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Flan casero tradicional con dulce de leche o crema",
    category: "postres",
    tags: ["Postre", "Flan"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    calories: 290,
    allergens: ["Lácteos", "Huevo"],
    stock: 35,
    is_available: true
  },
  {
    id: "pos-ensalada-frutas",
    name: "Ensalada de Frutas Fresca",
    price: 4000,
    takeaway_price: 3600,
    delivery_price: 4400,
    description: "Porción de ensalada de frutas frescas de estación",
    category: "postres",
    tags: ["Postre", "Frutas", "Saludable"],
    image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    calories: 160,
    allergens: [],
    stock: 40,
    is_available: true
  }
];

async function seedRealMenu() {
  console.log(`Starting real menu seed... Total items: ${REAL_MENU_ITEMS.length}`);

  // Set is_available = false for all old items first
  const { error: markError } = await supabase.from("menu_items").update({ is_available: false }).neq("id", "none");
  if (markError) {
    console.warn("Warning marking old items unavailable:", markError.message);
  } else {
    console.log("Deactivated previous menu items.");
  }

  // Upsert all new real menu items
  const { data, error: upsertError } = await supabase
    .from("menu_items")
    .upsert(REAL_MENU_ITEMS, { onConflict: "id" })
    .select();

  if (upsertError) {
    console.error("Error upserting real menu items:", upsertError);
  } else {
    console.log(`SUCCESS! Upserted ${data.length} real menu items in Supabase DB.`);
  }
}

seedRealMenu();
