import fs from "fs";
import path from "path";

const content = `import { MenuItem, Table } from "../types";

export const MENU_ITEMS: MenuItem[] = [
  // 🥐 1. DESAYUNOS Y MERIENDAS
  {
    id: "des-chico",
    name: "Desayuno / Merienda Chico",
    price: 3000,
    takeawayPrice: 2700,
    deliveryPrice: 3300,
    description: "Café, Cortado o Lágrima + 1 medialuna y 1 criollito",
    category: "desayunos_meriendas",
    tags: ["Desayuno", "Merienda"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 220, allergens: ["Gluten", "Lácteos"] },
    stock: 50,
    isAvailable: true,
    station: "barista"
  },
  {
    id: "des-jarro",
    name: "Desayuno / Merienda Jarro",
    price: 3500,
    takeawayPrice: 3150,
    deliveryPrice: 3850,
    description: "Café, Cortado o Lágrima en Jarro + 1 medialuna y 1 criollito",
    category: "desayunos_meriendas",
    tags: ["Desayuno", "Merienda"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 260, allergens: ["Gluten", "Lácteos"] },
    stock: 50,
    isAvailable: true,
    station: "barista"
  },
  {
    id: "des-grande",
    name: "Desayuno / Merienda Grande",
    price: 5500,
    takeawayPrice: 4950,
    deliveryPrice: 6050,
    description: "Café, Cortado o Lágrima + 2 medialunas y 2 criollitos",
    category: "desayunos_meriendas",
    tags: ["Desayuno", "Merienda", "Completo"],
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 450, allergens: ["Gluten", "Lácteos"] },
    stock: 50,
    isAvailable: true,
    station: "barista"
  },
  {
    id: "des-submarino-capuchino",
    name: "Submarino / Capuchino Especial",
    price: 6000,
    takeawayPrice: 5400,
    deliveryPrice: 6600,
    description: "Submarino de chocolate o Capuchino + 2 medialunas y 2 criollitos",
    category: "desayunos_meriendas",
    tags: ["Especial", "Chocolate"],
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 480, allergens: ["Gluten", "Lácteos"] },
    stock: 40,
    isAvailable: true,
    station: "barista"
  },
  {
    id: "des-te",
    name: "Servicio de Té Completo",
    price: 4500,
    takeawayPrice: 4050,
    deliveryPrice: 4950,
    description: "Té (consultar variedades) + 2 medialunas y 2 criollitos",
    category: "desayunos_meriendas",
    tags: ["Té", "Merienda"],
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 320, allergens: ["Gluten", "Lácteos"] },
    stock: 40,
    isAvailable: true,
    station: "barista"
  },
  {
    id: "des-super-completo",
    name: "Desayuno / Merienda Súper Completo",
    price: 7000,
    takeawayPrice: 6300,
    deliveryPrice: 7700,
    description: "Doble, Submarino, Capuchino o Té con tostadas, manteca, mermelada o dulce de leche y jugo de naranja",
    category: "desayunos_meriendas",
    tags: ["Súper Completo", "Recomendado"],
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 550, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "barista"
  },

  // ☕ 2. PROMOS
  {
    id: "pro-tostado",
    name: "Promo Infusión + Tostado",
    price: 10000,
    takeawayPrice: 9000,
    deliveryPrice: 11000,
    description: "Infusión fría o caliente + tostado mixto de jamón y queso",
    category: "desayunos_meriendas",
    tags: ["Promo", "Tostado"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 520, allergens: ["Gluten", "Lácteos"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pro-huevos-jamon",
    name: "Promo Infusión + Huevos Revueltos y Jamón",
    price: 12000,
    takeawayPrice: 10800,
    deliveryPrice: 13200,
    description: "Infusión fría o caliente + 2 huevos revueltos, 2 fetas de jamón y 2 fetas de queso",
    category: "desayunos_meriendas",
    tags: ["Promo", "Proteico"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 480, allergens: ["Huevo", "Lácteos"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🥟 3. EMPANADAS Y PIZZAS
  {
    id: "emp-carne",
    name: "Empanada de Carne",
    price: 2000,
    takeawayPrice: 1800,
    deliveryPrice: 2200,
    description: "Empanada criolla de carne cortada a cuchillo",
    category: "empanadas",
    tags: ["Empanadas", "Carne"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 250, allergens: ["Gluten"] },
    stock: 60,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "emp-pollo",
    name: "Empanada de Pollo",
    price: 2000,
    takeawayPrice: 1800,
    deliveryPrice: 2200,
    description: "Empanada de pollo sazonada",
    category: "empanadas",
    tags: ["Empanadas", "Pollo"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 230, allergens: ["Gluten"] },
    stock: 60,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "emp-jq",
    name: "Empanada de Jamón y Queso",
    price: 2000,
    takeawayPrice: 1800,
    deliveryPrice: 2200,
    description: "Empanada hojaldrada de jamón y muzzarella",
    category: "empanadas",
    tags: ["Empanadas"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 260, allergens: ["Gluten", "Lácteos"] },
    stock: 60,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "emp-caprese",
    name: "Empanada Caprese",
    price: 2000,
    takeawayPrice: 1800,
    deliveryPrice: 2200,
    description: "Empanada de muzzarella, tomate fresco y albahaca",
    category: "empanadas",
    tags: ["Empanadas", "Vegetariano"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 220, allergens: ["Gluten", "Lácteos"] },
    stock: 60,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🍕 PIZZAS
  {
    id: "piz-mozzarella",
    name: "Pizza Mozzarella",
    price: 14000,
    takeawayPrice: 12600,
    deliveryPrice: 15400,
    description: "Mozzarella, orégano y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Clásico"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 850, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-mozzarella-doble",
    name: "Pizza Mozzarella Doble",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella doble, orégano y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Doble Queso"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 1050, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-anchoa",
    name: "Pizza Anchoa",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, anchoas y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Anchoas"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 890, allergens: ["Gluten", "Lácteos", "Pescado"] },
    stock: 25,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-morron",
    name: "Pizza Morrón",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, morrón asado y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 870, allergens: ["Gluten", "Lácteos"] },
    stock: 25,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-jamon",
    name: "Pizza Jamón",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, jamón y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 920, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-especial",
    name: "Pizza Especial",
    price: 17000,
    takeawayPrice: 15300,
    deliveryPrice: 18700,
    description: "Mozzarella, jamón, morrón y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Especial"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 960, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-roquefort",
    name: "Pizza Roquefort",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, queso roquefort y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Roquefort"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 980, allergens: ["Gluten", "Lácteos"] },
    stock: 25,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-napolitana",
    name: "Pizza Napolitana",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, rodajas de tomate, orégano y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Napolitana"],
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 890, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-albahaca",
    name: "Pizza Albahaca",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, tomate picado, albahaca fresca y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Fresca"],
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 880, allergens: ["Gluten", "Lácteos"] },
    stock: 25,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-fugazza",
    name: "Pizza Fugazza",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Mozzarella, abundante cebolla rehogada y aceitunas verdes",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Fugazza"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 910, allergens: ["Gluten", "Lácteos"] },
    stock: 25,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-palmito",
    name: "Pizza Palmito",
    price: 18000,
    takeawayPrice: 16200,
    deliveryPrice: 19800,
    description: "Mozzarella, palmitos, salsa golf y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Especial"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 990, allergens: ["Gluten", "Lácteos"] },
    stock: 20,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-brasilera",
    name: "Pizza Brasilera",
    price: 18000,
    takeawayPrice: 16200,
    deliveryPrice: 19800,
    description: "Mozzarella, ananá, azúcar morena y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Agridulce"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 950, allergens: ["Gluten", "Lácteos"] },
    stock: 20,
    isAvailable: true,
    station: "parrilla"
  },
  {
    id: "piz-rucula",
    name: "Pizza Rúcula y Jamón Crudo",
    price: 18000,
    takeawayPrice: 16200,
    deliveryPrice: 19800,
    description: "Mozzarella, rúcula fresca, jamón crudo y aceitunas negras",
    category: "pizzas_focaccias",
    tags: ["Pizzas", "Gourmet"],
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 940, allergens: ["Gluten", "Lácteos"] },
    stock: 25,
    isAvailable: true,
    station: "parrilla"
  },

  // 🍝 4. PASTAS
  {
    id: "pas-noquis",
    name: "Ñoquis de Papa o Espinaca",
    price: 8500,
    takeawayPrice: 7650,
    deliveryPrice: 9350,
    description: "Ñoquis caseros con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 550, allergens: ["Gluten", "Huevo"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pas-ravioles",
    name: "Ravioles Caseros",
    price: 9000,
    takeawayPrice: 8100,
    deliveryPrice: 9900,
    description: "Ravioles caseros con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 580, allergens: ["Gluten", "Huevo"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pas-canelones",
    name: "Canelones Caseros",
    price: 8500,
    takeawayPrice: 7650,
    deliveryPrice: 9350,
    description: "Canelones caseros rellenos con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 620, allergens: ["Gluten", "Huevo", "Lácteos"] },
    stock: 25,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pas-tallarines",
    name: "Tallarines Caseros",
    price: 8500,
    takeawayPrice: 7650,
    deliveryPrice: 9350,
    description: "Tallarines caseros al huevo con salsa a elección (roja, rosa, boloñesa, blanca, mixta o crema)",
    category: "pastas_caseras",
    tags: ["Pastas", "Casero"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 520, allergens: ["Gluten", "Huevo"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🥩 5. AL PLATO
  {
    id: "pla-milanesa",
    name: "Milanesa al Plato (Ternera o Pollo)",
    price: 7000,
    takeawayPrice: 6300,
    deliveryPrice: 7700,
    description: "Milanesa dorada de ternera o pollo servida al plato",
    category: "minutas_carnes",
    tags: ["Al Plato", "Milanesa"],
    image: "https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 580, allergens: ["Gluten", "Huevo"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pla-milanesa-napolitana",
    name: "Milanesa Napolitana al Plato",
    price: 8000,
    takeawayPrice: 7200,
    deliveryPrice: 8800,
    description: "Milanesa de ternera o pollo a la napolitana con salsa de tomate, jamón y queso fundido",
    category: "minutas_carnes",
    tags: ["Al Plato", "Napolitana"],
    image: "https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 720, allergens: ["Gluten", "Huevo", "Lácteos"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pla-carre-cerdo",
    name: "Carré de Cerdo (2 unidades)",
    price: 8000,
    takeawayPrice: 7200,
    deliveryPrice: 8800,
    description: "2 unidades de carré de cerdo doradas y jugosas a la plancha",
    category: "minutas_carnes",
    tags: ["Al Plato", "Cerdo"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 640, allergens: [] },
    stock: 25,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "pla-costeleta-ternera",
    name: "Costeleta de Ternera (1 unidad)",
    price: 5000,
    takeawayPrice: 4500,
    deliveryPrice: 5500,
    description: "1 costeleta de ternera tierna sazonada a la plancha",
    category: "minutas_carnes",
    tags: ["Al Plato", "Ternera"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 450, allergens: [] },
    stock: 30,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🍟 6. GUARNICIONES
  {
    id: "gua-papas-fritas",
    name: "Papas Fritas",
    price: 5000,
    takeawayPrice: 4500,
    deliveryPrice: 5500,
    description: "Porción de papas fritas bastón doradas y crocantes",
    category: "minutas_carnes",
    tags: ["Guarnición", "Papas"],
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 420, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "gua-papas-huevo",
    name: "Papas Fritas con Huevo Revuelto",
    price: 8000,
    takeawayPrice: 7200,
    deliveryPrice: 8800,
    description: "Papas fritas crocantes coronadas con huevo revuelto",
    category: "minutas_carnes",
    tags: ["Guarnición", "Especial"],
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 580, allergens: ["Huevo"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "gua-pure",
    name: "Puré de Papa o Puré Mixto",
    price: 5000,
    takeawayPrice: 4500,
    deliveryPrice: 5500,
    description: "Puré cremoso casero de papa o mixto (papa y zapallo)",
    category: "minutas_carnes",
    tags: ["Guarnición", "Puré"],
    image: "https://images.unsplash.com/photo-1514944288352-fffac99f0bdf?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 280, allergens: ["Lácteos"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "gua-huevo-frito",
    name: "Huevo Frito (1 unidad)",
    price: 1000,
    takeawayPrice: 900,
    deliveryPrice: 1100,
    description: "1 unidad de huevo frito a punto",
    category: "minutas_carnes",
    tags: ["Guarnición"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 90, allergens: ["Huevo"] },
    stock: 60,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "gua-arroz",
    name: "Arroz Amarillo o Blanco c/ Queso y Crema",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Arroz amarillo sazonado o arroz blanco servido con queso y crema",
    category: "minutas_carnes",
    tags: ["Guarnición", "Arroz"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 310, allergens: ["Lácteos"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "gua-ensalada-mixta",
    name: "Ensalada Mixta",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Tomate, lechuga, zanahoria y huevo",
    category: "minutas_carnes",
    tags: ["Ensalada", "Fresca"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 140, allergens: ["Huevo"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_fria"
  },
  {
    id: "gua-ensalada-completa",
    name: "Ensalada Completa",
    price: 7000,
    takeawayPrice: 6300,
    deliveryPrice: 7700,
    description: "Tomate, lechuga, remolacha, zanahoria, rúcula, huevo, jamón, queso y pollo",
    category: "minutas_carnes",
    tags: ["Ensalada", "Completa"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 380, allergens: ["Huevo", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_fria"
  },

  // 🥪 7. LOMITOS
  {
    id: "lom-simple",
    name: "Lomito Simple c/ Papas (Ternera o Pollo)",
    price: 12000,
    takeawayPrice: 10800,
    deliveryPrice: 13200,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón y queso. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Lomito", "Con Papas"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 820, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "lom-completo",
    name: "Lomito Completo c/ Papas (Ternera o Pollo)",
    price: 13000,
    takeawayPrice: 11700,
    deliveryPrice: 14300,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso y huevo frito. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Lomito", "Completo"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 910, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "lom-teatro",
    name: "Lomito del Teatro c/ Papas",
    price: 14000,
    takeawayPrice: 12600,
    deliveryPrice: 15400,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso, huevo frito, morrón y cebolla salteada. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Lomito", "Especial de la Casa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 1020, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🍔 8. HAMBURGUESAS
  {
    id: "ham-simple",
    name: "Hamburguesa Simple c/ Papas",
    price: 10000,
    takeawayPrice: 9000,
    deliveryPrice: 11000,
    description: "Lechuga, tomate, mayonesa, jamón y queso. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Hamburguesa", "Con Papas"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 780, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "ham-completa",
    name: "Hamburguesa Completa c/ Papas",
    price: 11000,
    takeawayPrice: 9900,
    deliveryPrice: 12100,
    description: "Lechuga, tomate, mayonesa, jamón, queso y huevo frito. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Hamburguesa", "Completa"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 870, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 40,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "ham-teatro",
    name: "Hamburguesa del Teatro c/ Papas",
    price: 12000,
    takeawayPrice: 10800,
    deliveryPrice: 13200,
    description: "Lechuga, tomate, mayonesa, jamón, queso, huevo frito, morrón y cebolla salteada. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Hamburguesa", "Especial de la Casa"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 980, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🥖 9. SÁNDWICHES DE MILANESA
  {
    id: "san-milanesa-simple",
    name: "Sándwich de Milanesa Simple c/ Papas",
    price: 11000,
    takeawayPrice: 9900,
    deliveryPrice: 12100,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón y queso. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Sándwich", "Milanesa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 840, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "san-milanesa-completa",
    name: "Sándwich de Milanesa Completa c/ Papas",
    price: 12000,
    takeawayPrice: 10800,
    deliveryPrice: 13200,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso y huevo frito. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Sándwich", "Milanesa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 920, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "san-milanesa-teatro",
    name: "Sándwich de Milanesa del Teatro c/ Papas",
    price: 13000,
    takeawayPrice: 11700,
    deliveryPrice: 14300,
    description: "Ternera o pollo, lechuga, tomate, mayonesa, jamón, queso, huevo frito, morrón y cebolla salteada. Incluye papas fritas",
    category: "minutas_carnes",
    tags: ["Sándwich", "Especial de la Casa"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 1040, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🥪 10. SÁNDWICHES FRÍOS Y OTROS
  {
    id: "san-miga-2u",
    name: "Sándwiches de Miga (2 unidades)",
    price: 7000,
    takeawayPrice: 6300,
    deliveryPrice: 7700,
    description: "2 unidades de sándwich de miga + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Miga"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 420, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_fria"
  },
  {
    id: "san-arabe",
    name: "Sándwich Árabe (Jamón o Milanesa)",
    price: 6000,
    takeawayPrice: 5400,
    deliveryPrice: 6600,
    description: "Sándwich en pan árabe con jamón o milanesa + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Árabe"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 460, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_fria"
  },
  {
    id: "san-pebete",
    name: "Pebete (Jamón o Milanesa)",
    price: 6000,
    takeawayPrice: 5400,
    deliveryPrice: 6600,
    description: "Pebete tierno de jamón y queso o milanesa + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Pebete"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 440, allergens: ["Gluten", "Lácteos"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_fria"
  },
  {
    id: "san-pebeton",
    name: "Pebetón Gigante (Jamón o Milanesa)",
    price: 7000,
    takeawayPrice: 6300,
    deliveryPrice: 7700,
    description: "Pebetón de gran tamaño con jamón o milanesa + papas copetín",
    category: "minutas_carnes",
    tags: ["Sándwich", "Pebetón"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 580, allergens: ["Gluten", "Lácteos"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_fria"
  },

  // 🍽️ 11. MENÚ EJECUTIVO
  {
    id: "exe-para-llevar",
    name: "Menú Ejecutivo (Para Llevar)",
    price: 8000,
    takeawayPrice: 8000,
    deliveryPrice: 8800,
    description: "Plato principal del día preparado para llevar",
    category: "executive",
    tags: ["Menú Ejecutivo", "Para Llevar"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 650, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "exe-mesa-bebida",
    name: "Menú Ejecutivo + Bebida (En Mesa)",
    price: 12000,
    takeawayPrice: 10800,
    deliveryPrice: 13200,
    description: "Plato principal del día + bebida de la casa para consumo en salón",
    category: "executive",
    tags: ["Menú Ejecutivo", "Salón"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 720, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "cocina_caliente"
  },
  {
    id: "exe-completo",
    name: "Menú Ejecutivo Completo (Plato + Bebida + Postre)",
    price: 16000,
    takeawayPrice: 14400,
    deliveryPrice: 17600,
    description: "Plato principal del día + bebida + postre a elección para consumo en salón",
    category: "executive",
    tags: ["Menú Ejecutivo", "Completo"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 880, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "cocina_caliente"
  },

  // 🍹 12. BEBIDAS Y POSTRES
  // Jugos y Licuados
  {
    id: "beb-licuado-frutal",
    name: "Jugo / Licuado Frutal",
    price: 6000,
    takeawayPrice: 5400,
    deliveryPrice: 6600,
    description: "Durazno, Banana, Frutilla o Multifrutas al agua o con leche",
    category: "bebidas_sa",
    tags: ["Licuado", "Frutas"],
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 210, allergens: ["Lácteos"] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },

  // Gaseosas y Aguas
  {
    id: "beb-gaseosa-lata",
    name: "Gaseosa / Agua en Lata 354 ml",
    price: 3000,
    takeawayPrice: 2700,
    deliveryPrice: 3300,
    description: "Variedades de gaseosas o agua en lata 354 ml",
    category: "bebidas_sa",
    tags: ["Bebidas", "Sin Alcohol"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 140, allergens: [] },
    stock: 100,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "beb-gaseosa-500",
    name: "Gaseosa / Agua Botella 500 ml",
    price: 3500,
    takeawayPrice: 3150,
    deliveryPrice: 3850,
    description: "Botella individual de 500 ml",
    category: "bebidas_sa",
    tags: ["Bebidas", "Sin Alcohol"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 180, allergens: [] },
    stock: 100,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "beb-gaseosa-1L",
    name: "Gaseosa Botella 1 L / 1.25 L",
    price: 7000,
    takeawayPrice: 6300,
    deliveryPrice: 7700,
    description: "Botella grande de 1 Litro / 1.25 Litros",
    category: "bebidas_sa",
    tags: ["Bebidas", "Familiar"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 420, allergens: [] },
    stock: 60,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "beb-gatorade",
    name: "Gatorade / Powerade 500 ml",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Bebida isotónica hidratante 500 ml",
    category: "bebidas_sa",
    tags: ["Bebidas", "Isotónica"],
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 120, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },

  // Cervezas, Vinos y Tragos
  {
    id: "alc-cerveza-lata-473",
    name: "Cerveza en Lata 473 ml",
    price: 3500,
    takeawayPrice: 3150,
    deliveryPrice: 3850,
    description: "Cerveza rubia en lata de 473 ml",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Lata"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 210, allergens: ["Gluten"] },
    stock: 80,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-quilmes-1L",
    name: "Cerveza Quilmes 1 L",
    price: 7500,
    takeawayPrice: 6750,
    deliveryPrice: 8250,
    description: "Cerveza Quilmes de 1 Litro retornable bien helada",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "1 Litro"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 430, allergens: ["Gluten"] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-quilmes-stout-ipa",
    name: "Cerveza Quilmes Stout / IPA 1 L",
    price: 8000,
    takeawayPrice: 7200,
    deliveryPrice: 8800,
    description: "Cerveza Quilmes especial Stout negra o IPA de 1 Litro",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Especial"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 460, allergens: ["Gluten"] },
    stock: 40,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-andes-1L",
    name: "Cerveza Andes 1 L",
    price: 8000,
    takeawayPrice: 7200,
    deliveryPrice: 8800,
    description: "Cerveza Andes Origen de 1 Litro bien fría",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "1 Litro"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 440, allergens: ["Gluten"] },
    stock: 40,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-brahma-1L",
    name: "Cerveza Brahma 1 L",
    price: 7500,
    takeawayPrice: 6750,
    deliveryPrice: 8250,
    description: "Cerveza Brahma de 1 Litro bien helada",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "1 Litro"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 420, allergens: ["Gluten"] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-stella-heineken-1L",
    name: "Cerveza Stella Artois / Heineken 1 L",
    price: 8000,
    takeawayPrice: 7200,
    deliveryPrice: 8800,
    description: "Cerveza Stella Artois o Heineken Premium de 1 Litro",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Premium"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 440, allergens: ["Gluten"] },
    stock: 40,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-corona-chica",
    name: "Cerveza Corona Chica (330 ml)",
    price: 5500,
    takeawayPrice: 4950,
    deliveryPrice: 6050,
    description: "Porrón de cerveza Corona 330 ml servido con limón",
    category: "bebidas_alcohol",
    tags: ["Cerveza", "Porrón"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 150, allergens: ["Gluten"] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-corona-grande",
    name: "Cerveza Corona Grande (710 ml)",
    price: 6500,
    takeawayPrice: 5850,
    deliveryPrice: 7150,
    description: "Botella de cerveza Corona 710 ml servida con limón",
    category: "bebidas_alcohol",
    tags: ["Cerveza"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 320, allergens: ["Gluten"] },
    stock: 40,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-vino-botella",
    name: "Vino en Botella (750 ml)",
    price: 9000,
    takeawayPrice: 8100,
    deliveryPrice: 9900,
    description: "Vino de la casa seleccionado en botella 750 ml",
    category: "bebidas_alcohol",
    tags: ["Vino"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 520, allergens: [] },
    stock: 30,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-vino-copa",
    name: "Vino en Copa",
    price: 3000,
    takeawayPrice: 2700,
    deliveryPrice: 3300,
    description: "Copa de vino varietal de la casa",
    category: "bebidas_alcohol",
    tags: ["Vino", "Copa"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 120, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-fernet",
    name: "Fernet Branca con Coca",
    price: 6000,
    takeawayPrice: 5400,
    deliveryPrice: 6600,
    description: "Trago de Fernet Branca helado preparado con Coca-Cola",
    category: "bebidas_alcohol",
    tags: ["Trago", "Fernet", "Favorito"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 240, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },
  {
    id: "alc-gancia",
    name: "Gancia con Limón",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Trago aperitivo Gancia servido con hielo y rodaja de limón",
    category: "bebidas_alcohol",
    tags: ["Trago", "Aperitivo"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 180, allergens: [] },
    stock: 50,
    isAvailable: true,
    station: "barra_tragos"
  },

  // 🍰 POSTRES
  {
    id: "pos-budin-pan",
    name: "Budín de Pan Casero",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Budín de pan casero con dulce de leche o crema",
    category: "postres",
    tags: ["Postre", "Casero"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 320, allergens: ["Gluten", "Lácteos", "Huevo"] },
    stock: 30,
    isAvailable: true,
    station: "cocina_fria"
  },
  {
    id: "pos-flan-casero",
    name: "Flan Casero Tradicional",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Flan casero tradicional con dulce de leche o crema",
    category: "postres",
    tags: ["Postre", "Flan"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=600",
    customizable: true,
    nutrition: { calories: 290, allergens: ["Lácteos", "Huevo"] },
    stock: 35,
    isAvailable: true,
    station: "cocina_fria"
  },
  {
    id: "pos-ensalada-frutas",
    name: "Ensalada de Frutas Fresca",
    price: 4000,
    takeawayPrice: 3600,
    deliveryPrice: 4400,
    description: "Porción de ensalada de frutas frescas de estación",
    category: "postres",
    tags: ["Postre", "Frutas", "Saludable"],
    image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&q=80&w=600",
    customizable: false,
    nutrition: { calories: 160, allergens: [] },
    stock: 40,
    isAvailable: true,
    station: "cocina_fria"
  }
];

export const INITIAL_TABLES: Table[] = Array.from({ length: 15 }, (_, i) => ({
  id: i + 1,
  number: i + 1,
  capacity: i % 2 === 0 ? 4 : 2,
  status: "libre",
  zone: i < 5 ? "Planta Baja" : i < 10 ? "Mezzanine" : "Terraza"
}));
`;

fs.writeFileSync(path.join(process.cwd(), "src/data/menu.ts"), content, "utf8");
console.log("Updated src/data/menu.ts successfully!");
